Homework 1
VictorAlexKuznecov/introduction-to-javascript pull request #1
Opened 2024-02-14 03:24 UTC by VictorAlexKuznecov

Seven main tasks plus two additional ones were solved

2024-02-19 18:24 UTC, NikeLike101 requested changes

2024-02-19 18:24 UTC, NikeLike101 commented on main.js
> +  console.log(`Variable: ${number} have type: ${typeof number}`);
В задании подразумневалось вывести название переменной, доработай, пожалуйста)

2024-02-20 04:29 UTC, VictorAlexKuznecov commented on main.js
> +  console.log(`Variable: ${number} have type: ${typeof number}`);
Поправил)

2024-02-29 12:29 UTC, NikeLike101 commented
Проверено, молодец!)

2024-02-29 12:29 UTC, closed without merging